PatrickAmbrosso/Snippets@main:
  - dotfiles/
  - docker/
PatrickAmbrosso/Odysseus-Ambrosia@main:
  - source: dotfiles/
    dest: content/Snippets/dotfiles/
  - source: docker/
    dest: content/Snippets/docker/