PatrickAmbrosso/Snippets@main:
  - dotfiles/
  - docker/
PatrickAmbrosso/Odysseus-Ambrosia@main:
  - source: dotfiles/
    dest: content/Snippets/dotfiles/
    deleteOrphaned: true
  - source: docker/
    dest: content/Snippets/docker/
    deleteOrphaned: true